title: Sehsat Bozkurt | Digital Innovation
description: Transforming Business Knowledge into Actionable Success Strategies
logo: /uploads/logo.png
social:
  twitter: 
  facebook: 
  instagram: 
  linkedin: